train:
  lr: 0.0001
  num_steps: 20
  num_episodes: 1000
  partition: 10
  gamma: 0.98
  epsilon: 0.5
  target_update: 10
  batch_size : 8

  action_space_range_left: 0
  action_space_range_right: 2
  action_space_partition_num: 11

  exp_log_path: /root/autodl-tmp/log/
  exp_results_path: /root/autodl-tmp/runs/
  exp_imgs: /root/autodl-tmp/exp_imgs/

evalueate:
  pth_path: ./pth/q_net.pth
  test_data_dir_path: ./DataSet/

env:
  name: ImgEnv

DataSet:
  DataSetDir: ./DataSet/
  DataPath: ./DataSet/test1.jpg

algorithm:
  name: DoubleDQN

model:
  name: QNet
  hidden_dim: 128


ReplayBuffer:
  name: ReplayBuffer
  buffer_size: 500
  minimal_size: 8
